### ISSUE TITLE
Support more type of ssh-key

### ISSUE THREAD

**Issue by oToToT** [qazwsxedcrfvtg14/dsajudge#1]
According to [RFC 8709](https://tools.ietf.org/html/rfc8709#section-4) (for ed25519) and [RFC 5656](https://tools.ietf.org/html/rfc5656#section-3.1) (for ecdsa), I think it is not bad to simply accept more prefix of a ssh-key.

**Comment by qazwsxedcrfvtg14** [comment]
Done!
