### ISSUE TITLE
wrong unit in ssh display

### ISSUE THREAD

**Issue by oToToT** [qazwsxedcrfvtg14/dsajudge#3]
![image](https://user-images.githubusercontent.com/8341564/77734368-808c0080-7043-11ea-83fa-1706d28aa2ca.png)
I think that it should be 0.022s, not 0.022ms

**Comment by qazwsxedcrfvtg14** [comment]
Fixed with this commit 1cefdbf9548479f18955d70ebb02117350eee72b.
